# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Enables parallel compilation
org.gradle.parallel=true

# Caching and performance
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true

# AndroidX
android.useAndroidX=true
# Disable Jetifier if possible (most modern libs don't need it)
android.enableJetifier=false

# Kotlin style
kotlin.code.style=official

# Android specific optimizations
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=true
android.enableAppCompileTimeRClass=false
android.uniquePackageNames=false
